language: minimal
sudo: required
services:
- docker
before_script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
script:
- make push
env:
  global:
    secure: LsXjqsvHXd2TFwP9ExYwYh+MKQeJY1umA8+Oy8AdVT6bplf1PmsaeH2inNEvlYgjQTfIn5ILherWSsYJrbDfa4kI03KBX3SAhke0J/Kbyt1iIqkAsX5TiSdUyv76m/AK4E+5VbVSIiAHz8DfUlPFIuZVZq2AmA80lH+90O//nemHhBoSGeCarvsMeuqrEm9ZZ2KdpF8UJKVelObQP0PrBKdF1A/5Q6v93Kv2kTHGieX5sJKKqwA5fstulfskJhT0mkJKMJVaNpyhvsfvNbBVbWR4RL3A9EVlVFufa94J7HC102h8nlOkC5geS12reoasDrKdZ11p49JjcSYbPhkMhY/uID+7EfU1MObF9XNCTWi1MWQ8JWdO31Bv46Uaro4MPwPUlMgYRIVEB8rnXVzNP8x8wNLUMDYikjpdgFvgco3lttCzrEhg11hRG+X/YR5wOHC6VhpeTVjiOBbVDR0SgCgTXJGyN5e2Hgg/IzyIRusS2cjgn+OEsiA2TP9EIB463Cs1stSph7oJTcgNzcK9DxN3KcrTZcSNlN24JWXnIC3N6G0Mh+FMr6VglcwQEjSW58uEasKHlwKyjuVnkcF13sA7mjzSzajzf/gUQtqvNRmoWUtNwBy81LWsOYKn0kfo5vyW3fRxQ1lcPJqxsBdgspk3FfguVGPOyS/sduoP8KA=
